### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EvertonMelo**
language name correction.
For Portuguese. 

Font: https://en.wikipedia.org/wiki/Portuguese_language or 
Font: https://www.wolframalpha.com/input/?i=Portuguese&lk=1&rawformassumption=%22ClashPrefs%22+-%3E+%7B%22Language%22,+%22Portuguese%22%7D

### CODE REVIEW

**Comment by camilolunacom** [comment]
Thank for your help @EvertonMelo! (It's _source_ and not _font_, btw 😉)

**Comment by EvertonMelo** [comment]
joke aside @camilolunacom 
Does the "Portugeise" language exist?
the correct one is not "Portuguese"

**Comment by camilolunacom** [comment]
@EvertonMelo I'm not joking. I'm sincerely thanking you for noticing a mistake that many of us didn't! I don't have enough permissions in this repository to merge, but @ccmawo can you have a look at this please?

**Comment by ccmawo** [comment]
sorry, I didn't see it.

**Comment by EvertonMelo** [comment]
@ccmawo 

> `[Presenting the code to multiple developers with the purpose of reaching consensus about its acceptance is a simple form of software reviewing. ](https://en.wikipedia.org/wiki/Linus%27s_Law)`

**Comment by xsttx** [comment]
@EvertonMelo we practice holocracy, not consensus, as our decision making model.

**Pull request merged**
